### ISSUE TITLE
Project warnings

### ISSUE THREAD

**Issue by vcoutasso** [pastre/LearningJourney#16]
While contributing to the project I noticed some warnings running `make` and inside Xcode. 

They are nothing but a little annoyance, but fixing them shouldn't be difficult, and I'm willing to do it if that's okay. The warnings I noticed are as following:

Xcode complains about the target version of some pods and asks for manual intervention:
![image](https://user-images.githubusercontent.com/44986513/136108490-f910d768-452c-458f-a752-c2ae9217b651.png)
Some minor changes to `Podfile` should fix this automatically for us (see [this question](https://stackoverflow.com/questions/37160688/set-deployment-target-for-cocoapodss-pod) for reference).

And CocoaPods is also throwing these at me:
![image](https://user-images.githubusercontent.com/44986513/136109006-3d0939cc-0426-4b0d-a0f2-243e716ee4ce.png)

Lastly, there are some warnings related to `Gemfile`:
![image](https://user-images.githubusercontent.com/44986513/136109125-27b08597-6b00-418a-865c-d897ed87775e.png)

Two things are going on here, and the message hints at us how to fix the first problem (missing an explicit global source).
The second point is more of a suggestion. The gems are being installed globally to the system as far as I can tell, but it might be a better idea to specify a path inside the project to install them (similarly to how CoacoaPods creates a `Pods` directory)

**Comment by pastre** [comment]
Go for it!
